version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: auth-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: auth
      MYSQL_USER: auth
      MYSQL_PASSWORD: auth
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    container_name: chilktc-auth
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=auth-db
      - DB_PORT=3306
      - DB_DATABASE=auth
      - DB_USERNAME=auth
      - DB_PASSWORD=auth
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: chilktc-gateway
    restart: always
    depends_on:
      - auth
      - redis
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVER_HOST=chilktc-auth
      - AUTH_SERVER_PORT=8081
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  redis-data:
  mysql-data: