server:
  port: 8083

spring:
  application:
    name: notification
  config:
    import: optional:classpath:greenroom-templates.yml

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:notification}
    username: ${DB_USERNAME:auth}
    password: ${DB_PASSWORD:auth}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: ${kafka.servers:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.bs: 0
        spring.json.trusted.packages: "*"
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        fetch.min.bytes: 1
        spring.json.trusted.packages: "*"
